openapi: 3.0.0
info:
  title: Memori API
  version: 1.0.0
paths:
  /api/diaries:
    post:
      summary: 日記を追加
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                diary:
                  type: string
                  example: 今日のうどんは最高だった
      responses:
        "200":
          description: 作成された日記
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  diary:
                    type: string
                    example: 今日のうどんは最高だった
                  createdAt:
                    type: string
                    format: date-time
